name: Publish React Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker pour le front-end React
      - name: Build Docker image for React app
        run: docker build -f docker/Dockerfile.react -t alexischartier/front-test-quali--simu:latest .

      # Pousser l'image Docker sur Docker Hub z
      - name: Push Docker image
        run: docker push alexischartier/front-test-quali--simu:latest
